### ISSUE TITLE
got CertPathValidatorException....

### ISSUE THREAD

**Issue by AhmadVatani** [deeparteffects/deeparteffects-api-android-example#1]
when running app. i got below exception:
`com.amazonaws.mobileconnectors.apigateway.ApiClientException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found. (Service: null; Status Code: 0; Error Code: null; Request ID: null)`

**Comment by clarrat** [comment]
This error has been fixed. Please check.

**Comment by rajiraji123** [comment]
hiii my app is getting crashed after uploading the pic
