### ISSUE TITLE
app crashes due to Internal server problem

### ISSUE THREAD

**Issue by harshapulikollu** [deeparteffects/deeparteffects-api-android-example#2]
Every time I try to upload a pic with a style it says  processing and the app crashes

**Comment by mrmceduns** [comment]
Same problem here it keep crashing anytime i try to upload images!

**Comment by clarrat** [comment]
Do you have a stacktrace?

**Comment by clarrat** [comment]
Please send me the project to reproduce the error. Did you change the ApiKeys? Have you chosen a Usage Plan at developer.deeparteffects.com?

**Comment by rajiraji123** [comment]
> Every time I try to upload a pic with a style it says processing and the app crashes

have you got any solution for this???
